# we wish we could add a theme like this one
# theme: jekyll-theme-leap-day
# but we need to learn how to match them with layouts.


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  
# For local development, we build css with the "expanded" format to produce
# human-readable output for easier debugging.
sass:
  sass_dir: _scss
  style: expanded
  
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3
  - 
    scope:
      path: "dox"
      type: "pages"
    values:
      vssku: "Visual Studio 2022"
      vsver_min: "17.8"
      dotnetver1: ".NET 6"
      dotnetver2: ".NET 8"
      dotnetverNext: ".NET 9"
      vsImagesPath: "images/vs/"

      
collections:
  samples:
    output: true

