# we wish we could add a theme like this one
# theme: jekyll-theme-leap-day
# but we need to learn how to match them with layouts.


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  
# For local development, we build css with the "expanded" format to produce
# human-readable output for easier debugging.
sass:
  sass_dir: _scss
  style: expanded
  
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3
      vs_sku: "Visual Studio 2022"
      vs_requirements_url: "https://learn.microsoft.com/visualstudio/releases/2022/system-requirements"
      vs_ver_min: "17.8"
      dotnet_ver1: ".NET 6"
      dotnet_ver2: ".NET 8"
      dotnet_ver_next: ".NET 9"

      
collections:
  samples:
    output: true

